package com.bignerdranch.android.businessmanagement.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp


data class Contract(
    var title: String = "",
    var location: String = "",
    var rent: String = "",
    var start: String = "",
    var end: String = "",
    var duration: String = "",
    var note: String = "",
    var name: String = "",
    var phone: String = "",

    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
