package com.bignerdranch.android.businessmanagement.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp


data class Contract(
    var houseID: String = "",
    var location: String = "",
    var rent: String = "",
    var s_year: String = "",
    var s_month: String = "",
    var s_date: String = "",
    var e_year: String = "",
    var e_month: String = "",
    var e_date: String = "",
    var duration: String = "",
    var note: String = "",
    var name: String = "",
    var phone: String = "",

    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
