package com.bignerdranch.android.businessmanagement.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class House(
    var id: String = "",

    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId
    var firestoreID: String = ""
) {
    override fun equals(other: Any?) : Boolean =
        if (other is House) {
            id == other.id
        } else {
            false
        }
}
